### ISSUE TITLE
non existing fetch tool

### ISSUE THREAD

**Issue by oblitum** [jashank/tarpaulin#1]
The makefile for downloading fonts doesn't work for me (Archlinux), I've replaced fetch with wget inside makefile. Also, I had to make each of the fonts to download all of them since there's no `make all` target.

OT: Can you give me a tip on how to remove/crop all of that surrounding page crop rules and symbols (take out the extra margins)? I'd like to have a clean page with almost no margin to read it in my cellphone.

**Comment by jashank** [comment]
Hi, and apologies for the delayed reply!

I've pushed a patch replacing fetch with wget; I have `fetch(1)` on most of my boxes, so hadn't noted this issue.  The default target in the fonts Makefile is `.stamp` which depends on all the font files being present; you should be able to run `make` and have all the fonts arrive.

To remove the cam marks, comment line 111 of tarpaulin.tex (comments in TeX are `%` to end of line). To amend the margins and geometry, twiddle the knobs on lines 103 through 110 of the same.

HTH!

**Comment by oblitum** [comment]
Thanks, I'd just like to comment about the `build.sh` script, currently if there's no `src` directory in the working copy, the script will copy Rust docs to the wrong place. It will put `docs` at `src`, instead of `src/docs`.
